config/routes.rb
Rails.application.routes.draw do
  
# root 'players#index'
# root 'messaging#index'
# root to: 'flags#test'
# get  'user_stream' => 'flags#index_stream'
# get 'test' => 'messaging#send_message'
# get 'reception'
   
  root 'players#new'
 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  get 'flag' => 'flags#new'    
  post 'flag' => 'flags#create'
    
  resources :players  
    
  get 'signup'  => 'players#new'
#  get 'stream' => 'players#stream'
        
end
 

app/models/flag.rb
class Flag < ActiveRecord::Base
    has_many :player_flags
    has_many :players, through: :player_flags  
end

app/models/player.rb
class Player < ActiveRecord::Base
    has_many :player_flags
    has_many :flags, through: :player_flags  

end

app/models/player_flag.rb
class PlayerFlag < ActiveRecord::Base
    belongs_to :player
    belongs_to :flag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  include ActionController::MimeResponds
  include ActionController::ImplicitRender
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    
    protect_from_forgery with: :exception
    
    helper_method :current_player 
    
    def current_player 
      @current_player ||= Player.find(session[:player_id]) if session[:player_id] 
    end
  
    def require_player 
      redirect_to '/login' unless current_player 
    end
        
end

app/controllers/flags_controller.rb
class FlagsController < ApplicationController
    include ActionController::Live   

    def new
    end
    
    def test
    end
    
    
    def create
        
        @flag = Flag.find_by_value(params[:session][:flag])
        @current_player = Player.find_by_id(session[:player_id])
            
        unless @flag && @current_player.flags.exists?(id: @flag.id)       
            if (@flag && @flag.value == params[:session][:flag])
    
                @current_player.no_flag += 1
                @current_player.timer = @current_player.timer + 600
                @current_player.points += @flag.weight
                @current_player.save
                @current_player.flags << @flag                
                # Streaming results
#                response.headers['Content-Type'] = 'text/event-stream'
#                sse = Reloader::SSE.new(response.stream)
#                begin
#                    sse.write({ :event => "refresh" })
#                    rescue IOError
#                    ensure
#                        sse.close
#                end

#               Display the right Message
                case @flag.id 
                when 1    
                    flash[:notice] = "Well done! You found the Terrorist's NAME" 
                when 2    
                    flash[:notice] = "Well done! You found the CONTINENT" 
                when 3    
                    flash[:notice] = "Well done! You found the COUNTRY" 
                when 4    
                    flash[:notice] = "Well done! You found the CITY" 
                when 5    
                    flash[:notice] = "Well done! You found the STREET NAME" 
                when 6    
                    flash[:notice] = "Well done! You found the STREET NUMBER" 
                when 7    
                    flash[:notice] = "Well done! You found the ZIP CODE" 
                when 8    
                    flash[:notice] = "Well done! You found the BOMB CODE" 
                end 
 
                redirect_to @flag
                
            else
                flash[:alert] = "Wrong flag !!"                
                redirect_to '/flag'
            end 
            
        else 
                flash[:alert] = "Flag already submitted !!"                
                redirect_to '/flag'
        end

    end 
    
    
end

app/controllers/messaging_controller.rb
require 'reloader/sse'

class MessagingController < ApplicationController
  include ActionController::Live

  def send_message
    response.headers['Content-Type'] = 'text/event-stream'
    sse = Reloader::SSE.new(response.stream)
    begin
      loop do
           ActiveSupport::Notifications.subscribe 'update' do |name, start, finish, id, payload|
           sse.write("Hello")
           puts "update"
           end
      sleep 1

    end
    rescue IOError
    ensure
      sse.close
    end
  end

    def reception
       ActiveSupport::Notifications.subscribe "update" do |name, start, finish, id, payload|
       puts ("test")
       end
    end

end

app/controllers/players_controller.rb
#require 'rails/sse'
require 'reloader/sse'

class PlayersController < ApplicationController
    include ActionController::Live
    
    def index
        @players = Player.all
    end
    
    def new
        @player = Player.new
    end
    
    def create
        @player = Player.new(player_params)
        if @player.save
            session[:player_id] = @player.id
            redirect_to '/flag'
        else
            redirect_to '/signup'
        end
    end
    
    def stream
        response.headers['Content-Type'] = 'text/event-stream'
        sse = Reloader::SSE.new(response.stream)
        begin 
            loop do
                sse.write("sss")
                sleep 5.second
            end
        end
    end
    
    
#   Pevent from mass assignment vulnerabilities
    private
        def player_params
          params.require(:player).permit(:name, :email, :password)
        end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end
    
    def create
        @player = Player.find_by_email(params[:session][:email].downcase)
        if @player && @player.password == params[:session][:password]
            session[:player_id] = @player.id
            redirect_to '/flag'
        else
            redirect_to '/login'
        end 
    end
        
    def destroy 
        session[:player_id] = nil 
        redirect_to '/' 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flags_helper.rb
module FlagsHelper
end

app/helpers/messaging_helper.rb
module MessagingHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/flags/new.html.erb
<body>
    
    <div class="container-fluid" id="main-back-flags">
<!-- Header Menu -->
        <nav class="navbar color1">
            <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                <% if current_player %> 
                    <a class="navbar-brand" href="#">Hi <%= current_player.name %> !</a>
                    <ul class="nav navbar-nav pull-right">
                        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                    </ul>
                <% else %>
                    <ul class="nav navbar-nav pull-right">
                        <li><%= link_to "Login", 'login' %></a></li> 
                        <li><%= link_to "Signup", 'signup' %></a></li> 
                    </ul>
                <% end %>
                </div> 
            </div>
        </nav> 

<!--Form to create account-->

            <div class="row"> 
                <p class="text-center form-title">Send a valid flag <br> and get some extra time </p> 
                <div class="col-md-4 col-sm-4 col-md-offset-4 col-sm-offset-4 form-wrapper">
                    <%= form_for :session, url: flag_path, :html => {:class => "form-horizontal center"} do |f| %>
                        <div class="form-group">
                            <div class="input-group">
                                <%= f.text_field :flag,  :placeholder => "Flag", class: 'form-control' %> 
                                <span class="input-group-addon"><i class="fa fa-flag"></i></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <%= f.submit "Send the flag", class: "btn btn-send btn-block" %>
                        </div>
                   <% end %>
               </div>
               <div class="col-md-4 col-sm-4 col-md-offset-4 col-sm-offset-4">
                    <% if notice %>
                        <p id="notice" class="alert alert-success text-center"><%= notice %></p>
                    <% end %>
                    <% if alert %>
                        <p id="alert" class="alert alert-danger text-center"><%= alert %></p>
                    <% end %>
               </div>
          </div>
            



    </div>

</body>

app/views/flags/test.html.erb
ipadfjpiadj

<!--
<ul id="users">
</ul>

#<%= content_for :javascript do %>
  <script type="text/javascript">
    var source = new EventSource('/user_stream');
    source.addEventListener('results', function(e){
      console.log('Received a message:', e.data);
      $("#users").append("<li>"+ $.parseJSON(e.data).name +"</li>");
    });
    source.addEventListener('finished', function(e){
      console.log('Close:', e.data);
      source.close();
    });
</script>
#<% end %>
-->
<html>
<div id="serverData">
  
</div>
    
<div id="serverData2">
  
</div>

</html>

<!--
  <script type="text/javascript">
        //functions here
        //check for browser support
        if(typeof(EventSource)!=="undefined") {
            //create an object, passing it the name and location of the server side script
            var eSource = new EventSource("/create");
            //detect message receipt
//            eSource.addEventListener("hacker1", function(event) {
//                //write the received data to the page
//                document.getElementById("serverData").innerHTML = event.data;
//            }, false); 
//            
//            eSource.addEventListener("hacker2", function(event) {
//                //write the received data to the page
//                document.getElementById("serverData2").innerHTML = event.data;
//            }, false); 
            
            //Reload webpage
            eSource.addEventListener("refresh", function(event) {
                //write the received data to the page
                window.location.reload();
            }, false);        
        }

        else {
            document.getElementById("serverData").innerHTML="Whoops! Your browser doesn't receive server-sent events.";
        }      
  </script>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackfest 2015</title>
    <!-- Refresh the page -->
    <meta http-equiv="refresh" content="5000" />
    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    
    <!-- Google Fonts -->  
    <link href='https://fonts.googleapis.com/css?family=Orbitron:400,500,700,900' rel='stylesheet' type='text/css'>    
    <script src="countdown.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    
    
</head>

<body>
    
    <%= yield %>
    
</body>

</html>

app/views/messaging/index.html.erb
<%= form_tag messaging_path, :method => 'get' do %>

    <%= text_field_tag :message, params[:message] %>
    <%= submit_tag "Post Message" %>

<% end %>

app/views/messaging/reception.html.erb
tt

app/views/players/index.html.erb
<body>
    <div class="container-fluid" id="main-back">
        <div class="container container-result row">
            <% @players.each do |p| %>           
                <div class="col-md-2">
                    <%= image_tag p.avatar, height: '100%', width: '100%', :class => "img-circle avatar-back"%>
                    <div class="thumbnail">
                        <div class="caption text-center text-uppercase">
                            <strong><%= p.name %><br>Flags: <%= p.no_flag %>/10<br>Score: <%= p.points %></strong>
                        </div>
                    </div>
                    <div class="thumbnail text-center countdown-wrapper text-uppercase">        
                        <strong>Time Bomb</strong>
                        <script type="application/javascript">
                                var myCountdown2 = new Countdown({
                                        time: <%= p.timer - (Time.now - p.created_at) %>, 
                                        width:135, 
                                        height:50, 
                                        style:"flip",
                                        rangeHi:"hour",	
                                        onComplete	: countdownComplete // <- no comma on last item!
                                        });
                                function countdownComplete(){
	                                   $(".thumbnail").css("background-color", "red");
                                       $(".avatar-back").css("background-color", "red");
                                       $(".avatar-back").css("opacity", "0.2");
                                        }

                        </script> 
                        <script type="text/javascript">
                            //functions here
                            //check for browser support
                            if(typeof(EventSource)!=="undefined") {
                                //create an object, passing it the name and location of the server side script
                                var eSource = new EventSource("/create");
  
                                eSource.addEventListener("hacker1", function(event) {
                                    //write the received data to the page
                                    alert(event.data);
                                }, false);        

                                    }

                                    else {
                                        document.getElementById("serverData").innerHTML="Whoops! Your browser doesn't receive server-sent events.";
                                    }      
                        </script>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
  </body>

app/views/players/new.html.erb
<head>
    <!-- <msdropdown> -->
    <link rel="stylesheet" type="text/css" href="msdropdown/dd.css" />
    <script src="msdropdown/jquery.dd.js"></script>
</head>

<body>    
    <div class="container-fluid" id="main-back-flags">
        <!-- Header Menu -->
        <nav class="navbar color1">
            <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                <% if current_player %> 
                    <a class="navbar-brand" href="#">Hi <%= current_player.name %> !</a>
                    <ul class="nav navbar-nav pull-right">
                        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                    </ul>
                <% else %>
                    <ul class="nav navbar-nav pull-right">
                        <li><%= link_to "Login", '/login' %></a></li> 
                        <li><%= link_to "Signup", '/signup' %></a></li> 
                    </ul>
                <% end %>
                </div> 
            </div>
        </nav> 

            <!--Form to create account-->
            <div class="row"> 
                <div class="col-md-4 col-sm-4 col-md-offset-4 col-sm-offset-4 form-wrapper">
                    <p class="text-center form-title">Create your Account</p>
                    <p class="text-center form-text">and start hacking ...</p>
                    <%= form_for @player, :html => {:class => "form-horizontal center"} do |p| %>
<!--
                        <table>
                            <tr>
                                <td valign="top">
                                    <select id="avatar" name="avatar" class= "text-center" style="width:100px;">
                                       <option value="" data-description="Select your avatar"></option>
                                         <option value="A01" data-image="assets/avatars/Males/N04i.png"></option>
                                         <option value="C04" data-image="assets/avatars/Males/C04i.png"></option>
                                         <option value="A01" data-image="assets/avatars/Males/N04i.png"></option>
                                         <option value="C04" data-image="assets/avatars/Males/C04i.png"></option>                                                        <option value="A01" data-image="assets/avatars/Males/N04i.png"></option>
                                         <option value="C04" data-image="assets/avatars/Males/C04i.png"></option> 
                                    </select>
                                </td>
                            </tr>
                        </table>
-->
                        <div class="form-group">
                            <div class="input-group">
                                <%= p.text_field :name, :placeholder => "Name", class: "form-control" %>
                                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <%= p.email_field :email, :placeholder => "Email", class: "form-control"%>
                                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="input-group">
                                <%= p.password_field :password, :placeholder => "Password", class: "form-control" %>
                                <span class="input-group-addon"><i class="fa fa-key"></i></span>                            
                            </div>
                        </div>
                        <div class="form-group">
                            <%= p.submit "Create an account", class: "btn btn-send btn-block" %>
                        </div>
                    <% end %>
                    <tr>
                        <td valign="top"><div id="byjson"></div></td>
                    </tr>
                </div>
            </div>
    </div>
</body>

<!--Script for dropdown menu-->
<script>
$(document).ready(function(e) {		
	//no use
	try {
		var pages = $("#pages").msDropdown({on:{change:function(data, ui) {
												var val = data.value;
												if(val!="")
													window.location = val;
											}}}).data("dd");

		var pagename = document.location.pathname.toString();
		pagename = pagename.split("/");
		pages.setIndexByValue(pagename[pagename.length-1]);
		$("#ver").html(msBeautify.version.msDropdown);
	} catch(e) {
		//console.log(e);	
	}
	
	$("#ver").html(msBeautify.version.msDropdown);
		
	//convert
	$("select").msDropdown({roundedBorder:false});
	createByJson();
	$("#tech").data("dd");
});
function showValue(h) {
	console.log(h.name, h.value);
}
$("#tech").change(function() {
	console.log("by jquery: ", this.value);
})
//
</script>